### ISSUE TITLE
[Collection] Broken menu swap items

### ISSUE THREAD

**Issue by Owain94** [runelite-extended/runelite#1234]
Recently we merged commit #1190 which uses priority swaps where possible to improve the performance of this plugin, because there was a performance hit when there were a lot of options present.

Because this is a rather large change we expect there are some options not working, most of them should just work fine though.

This issue is meant to collect all the broken swaps caused by the merge of that pull request.

**Comment by Owain94** [comment]
Withdraw X

**Comment by HSJ-OSRS** [comment]
swap admire applies to all instead of just cape racks

**Comment by Ganom** [comment]
> 
> 
> swap admire applies to everything instead of just mounted capes

What are the proper targets for the mounted capes?

**Comment by Trilligy** [comment]
Fairy rings

**Comment by Trilligy** [comment]
Birdhouses

**Comment by Trilligy** [comment]
Elkoy follow out of maze

**Comment by JourneyOver** [comment]
Blackjacking broke as well with this.

When the PR merged in, the first option always remains as "Pickpocket", if I revert the PR it works correctly by doing the "knock-out" as the first option always and then moves "pickpocket" up once you knock them out.

**Comment by Lucwousin** [comment]
Bankers get priority over grand exchange clerks, even if the ge person is in front of the banker.

https://i.imgur.com/fIQZqIL.png

**Comment by Ganom** [comment]
> 
> 
> Bankers get priority over grand exchange clerks, even if the ge person is in front of the banker.
> 
> https://i.imgur.com/fIQZqIL.png

That's going to be a tough one to solve, i could assign a higher priority to exchange as a band-aid fix. but the issue will then be present for bankers.

**Comment by Ganom** [comment]
> 
> 
> Blackjacking broke as well with this.
> 
> With the PR merged in, the first option always remains as "Pickpocket", if I revert the PR it works correctly by doing the "knock-out" as the first option always and then moves "pickpocket" up once you knock them out.

Relatively simple fix, we can assign higher priority for the menus in blackjack plugin.

**Comment by JourneyOver** [comment]
The `Pay (tree patch)` for Rosie in the farming guild is another one.

**Comment by bigmemes420** [comment]
Collect/Bank in the GE interface

**Comment by bigmemes420** [comment]
"Exchange is prioritized over banking"
https://media.nullcoreproject.net/i/387f86bb.png

**Comment by bigmemes420** [comment]
Occasionally all my left click options just because "use"

**Comment by sunha7** [comment]
the trade option prioritises over assignment on slayer masters
this is post adding priority values, did a pull today
https://i.imgur.com/3JuWHyg.jpg

**Comment by Ganom** [comment]
> 
> 
> "Exchange" is prioritized over banking
> https://media.nullcoreproject.net/i/387f86bb.png
> This is only when they overlap

Intended functionality.

**Comment by Ganom** [comment]
> 
> 
> Occasionally all my left click options just because "use"
> Seems to happen after trying to change shift click options

Shift click is indeed broken atm.

**Comment by Lucwousin** [comment]
> 
> 
> > "Exchange" is prioritized over banking
> > https://media.nullcoreproject.net/i/387f86bb.png
> > This is only when they overlap
> 
> Intended functionality.

Don't think this is intended actually :S

**Comment by Ganom** [comment]
> 
> 
> > > "Exchange" is prioritized over banking
> > > https://media.nullcoreproject.net/i/387f86bb.png
> > > This is only when they overlap
> > 
> > 
> > Intended functionality.
> 
> Don't think this is intended actually :S

```java
		if (this.swapBankExchange)
		{
			menuManager.addPriorityEntry("Bank").setPriority(1);
			menuManager.addPriorityEntry("Exchange").setPriority(10);
		}
```

**Comment by Kyleeld** [comment]
When any jewellery swapping is active, if the option matches another teleport option it ignores the fact it’s looking for jewellery .

To replicate: 

set ring of wealth to grand exchange
When using a varrock tab, this defaults left click to grand exchange
Change ring of wealth to varrock
Varrock tab stays stuck on GE until restarting plugin

**Comment by sunha7** [comment]
Shift Climb-Up from Climb Option

**Comment by Ganom** [comment]
Critical: Search swap overwrites construction swaps.

**Comment by Ganom** [comment]
Current swaps missing: 

- [ ] Abyss teleport
- [ ] Charters

**Comment by wongfluent** [comment]
Bank/Exchange menu swap causing Grand Exchange Clerk issue

Collecting items once purchased from inside transaction, banks instead of collect-item or collect-note.

![RuneLitePlus_2019-08-16_01-30-35](https://user-images.githubusercontent.com/22825474/63145503-bbb25580-bfc5-11e9-8a96-7dce17ee7997.png)

**Comment by Ganom** [comment]
> 
> 
> Bank/Exchange menu swap causing Grand Exchange Clerk issue
> 
> Collecting items once purchased from inside transaction, banks instead of collect option
> 
> ![RuneLitePlus_2019-08-16_01-30-35](https://user-images.githubusercontent.com/22825474/63145503-bbb25580-bfc5-11e9-8a96-7dce17ee7997.png)

fixed.

**Comment by xanderqixter** [comment]
Slayer ring left click teleport not working, maybe not counted as teleport item

**Comment by Jackyfalyfe** [comment]
Shift click walk under stops working a few a minutes of usage. (Closed client and still happens)

**Comment by calebcrowe** [comment]
> > Bank/Exchange menu swap causing Grand Exchange Clerk issue
> > Collecting items once purchased from inside transaction, banks instead of collect option
> 
> fixed.

Collecting items from a transaction is still an issue for me. With the "talk to" option swapped to "bank/exchange" enabled, items in the GE are swapping "collect" to "bank"

**Comment by absywabsy** [comment]
Withdraw/Deposit X is broken today:
https://i.imgur.com/5D7DcJC.gifv

**Comment by wongfluent** [comment]
> > Bank/Exchange menu swap causing Grand Exchange Clerk issue
> > Collecting items once purchased from inside transaction, banks instead of collect option
> 
> fixed.

It still seems to be an issue for me. It is still bank instead of collect

**Comment by dinosoup1** [comment]
The EZ construction swap completely broke for me today. Before it showed at least remove as the first option, now today, neither build nor remove are the first available options.

**Comment by Ganom** [comment]
> The EZ construction swap completely broke for me today. Before it showed at least remove as the first option, now today, neither build nor remove are the first available options.

Nothing regarding ez construction was changed, something may be overwriting the swap, like search for larders.

**Comment by HypoxiaOSRS** [comment]
Custom Swaps  use, Bones: drop, Bones
Doesn't work and neither does Glory/Teleport

**Comment by Owain94** [comment]
> Withdraw/Deposit X is broken today:
> [i.imgur.com/5D7DcJC.gifv](https://i.imgur.com/5D7DcJC.gifv)

This is an user error, withdraw X works fine

**Comment by HypoxiaOSRS** [comment]
Morytania Legs 3 should have an exception to default to Burgh teleport over Ecto. It overrides custom swap unless Teleport Items is disabled.
