### ISSUE TITLE
pluginorganizer: toggling hide plugins changes location of runeliteplus plugin

### ISSUE THREAD

**Issue by ThatGamerBlue** [runelite-extended/runelite#1343]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Turning hide plugins on and off moves RuneLitePlus from near the top to just below the colored plugins

**To Reproduce**
1. Go to Plugin Organizer
2. Turn on hide plugins
3. Turn it off

**Expected behavior**
RuneLitePlus plugin would remain at the top

**Comment by Kyleeld** [comment]
That should have been fixed

**Comment by Kyleeld** [comment]
#872 

Can you confirm you have that still? I can’t replicate

**Comment by ThatGamerBlue** [comment]
only seems to restore the position of the runelite plugin, runeliteplus still gets moved down https://i.imgur.com/cvYe7Zm.png

**Comment by Kyleeld** [comment]
fixed
