### ISSUE TITLE
slayer show monster weakness triggers randomly

### ISSUE THREAD

**Issue by xperiaclash** [runelite-extended/runelite#429]
**Describe the bug**
monter weakness is shown on random slayer targets like baby blacks and elf mourners

**To Reproduce**
1 - slayer plugin
2 - enable show monster weakness 
3 - face mourners/baby blacks

**Expected behavior**
shouldn't happen

**Screenshots**
https://gyazo.com/86d31ed3ec56fed97073491e6ce702fb

**Environment (please complete the following information):**
 - OS: [Windows]
 - RuneLite version: [latest]
 - Launcher version: [latest]

**Comment by Ganom** [comment]
This is related to wiki scraping, it is fixed now.

**Comment by SRLJustin** [comment]
sorry for replying to a closed issue, when was this fixed? I had Black Dragons as a task yesterday and was killing Baby Black Dragons for the task and the icon was still showing up when the NPC was doing the death animation

**Comment by Ganom** [comment]
> 
> 
> sorry for replying to a closed issue, when was this fixed? I had Black Dragons as a task yesterday and was killing Baby Black Dragons for the task and the icon was still showing up when the NPC was doing the death animation

Can you send me the npc id? We scrape the wiki for all monster stats, so it's possible they fucked something up.

**Comment by SRLJustin** [comment]
NPC ID: 1872
![image](https://user-images.githubusercontent.com/1625140/60385467-bd36c580-9acc-11e9-99c6-b09cc1d4b817.png)

I can't get animations as I am currently off-task

**Comment by Ganom** [comment]
```json
  "1872": {
    "name": "Baby dragon",
    "hitpoints": 80,
    "combatLevel": 83,
    "slayerLevel": 1,
    "attackSpeed": 4,
    "attackLevel": 70,
    "strengthLevel": 70,
    "defenceLevel": 70,
    "rangeLevel": 1,
    "magicLevel": 1,
    "stabDef": 30,
    "slashDef": 50,
    "crushDef": 50,
    "rangeDef": 30,
    "magicDef": 40,
    "dragon": true
  },
```

That is very odd that its still showing up after latest scraps.

**Comment by SRLJustin** [comment]
Ok, Can you please keep this issue open until further reply? I'll try and get Black Dragons asap as a task and we can sort out some extra debugging if you wish? Just hard to do as I only get assigned 10-14 to kill

**Comment by Ganom** [comment]
> 
> 
> Ok, Can you please keep this issue open until further reply? I'll try and get Black Dragons asap as a task and we can sort out some extra debugging if you wish? Just hard to do as I only get assigned 10-14 to kill

Check if they change id on death, and also grab animation on death if possible <3

**Comment by sdburns1998** [comment]
This was a problem before the NPC stats I think it has to do with my huge slayer plugin update from way back

I’m might have an idea what the problem could be we’ll discuss on discord @ganom

**Comment by Kyleeld** [comment]
https://imgur.com/ghYZBLK
